<?php

return array (
  'version' => '6.1.1',
  'title' => 'Floorplans',
  'type' => 'floorplans',
  'id' => '6048fca7a7894',
  'updated' => 1684983378,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '350',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '603352fca8b438' => 
    array (
      'type' => 'column-meta',
      'label' => 'Floorplan Source',
      'width' => '',
      'width_unit' => '%',
      'field' => 'floorplan_source',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '603352fca8b438',
    ),
    '646ecd2633b644' => 
    array (
      'type' => 'column-meta',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'field' => 'property_id',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecd2633b644',
    ),
    '6065196829374c' => 
    array (
      'type' => 'column-meta',
      'label' => 'Voyager Property Code',
      'width' => '',
      'width_unit' => '%',
      'field' => 'voyager_property_code',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6065196829374c',
    ),
    '646ecd146d0e58' => 
    array (
      'type' => 'column-meta',
      'label' => 'Floorplan ID',
      'width' => '',
      'width_unit' => '%',
      'field' => 'floorplan_id',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecd146d0e58',
    ),
    '646ecca6c04188' => 
    array (
      'type' => 'column-meta',
      'label' => 'Unit Type',
      'width' => '',
      'width_unit' => '%',
      'field' => 'unit_type_mapping',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecca6c04188',
    ),
    '646ecc804d9168' => 
    array (
      'type' => 'column-meta',
      'label' => 'Manual Images',
      'width' => '',
      'width_unit' => '%',
      'field' => 'manual_images',
      'field_type' => 'library_id',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'media_link_to' => '',
      'number_of_items' => '3',
      'before' => '',
      'after' => '',
      'edit' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecc804d9168',
    ),
    '646ecce8272b04' => 
    array (
      'type' => 'column-meta',
      'label' => 'Floorplan Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'floorplan_description',
      'field_type' => 'excerpt',
      'string_limit' => 'character_limit',
      'character_limit' => '60',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecce8272b04',
    ),
    '646ecd8d6353f8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Video/Tour',
      'width' => '',
      'width_unit' => '%',
      'field' => 'floorplan_video_or_tour',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecd8d6353f8',
    ),
    '646ecd9ca10624' => 
    array (
      'type' => 'column-meta',
      'label' => 'Beds',
      'width' => '',
      'width_unit' => '%',
      'field' => 'beds',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecd9ca10624',
    ),
    '646ecda7cc0830' => 
    array (
      'type' => 'column-meta',
      'label' => 'Baths',
      'width' => '',
      'width_unit' => '%',
      'field' => 'baths',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecda7cc0830',
    ),
    '646ecdb3a51eb8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Min Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'minimum_deposit',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecdb3a51eb8',
    ),
    '646ecdc0516874' => 
    array (
      'type' => 'column-meta',
      'label' => 'Max Deposit',
      'width' => '',
      'width_unit' => '%',
      'field' => 'maximum_deposit',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecdc0516874',
    ),
    '646ecdcea04188' => 
    array (
      'type' => 'column-meta',
      'label' => 'Min Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'minimum_rent',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecdcea04188',
    ),
    '646ecdd9d99998' => 
    array (
      'type' => 'column-meta',
      'label' => 'Max Rent',
      'width' => '',
      'width_unit' => '%',
      'field' => 'maximum_rent',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecdd9d99998',
    ),
    '646ecde40b4394' => 
    array (
      'type' => 'column-meta',
      'label' => 'Min Sqrft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'minimum_sqft',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecde40b4394',
    ),
    '646ecdf4516874' => 
    array (
      'type' => 'column-meta',
      'label' => 'Max Sqrft',
      'width' => '',
      'width_unit' => '%',
      'field' => 'maximum_sqft',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ecdf4516874',
    ),
    '646ece03e978d4' => 
    array (
      'type' => 'column-meta',
      'label' => 'Availability Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'availability_date',
      'field_type' => 'date',
      'date_format' => 'wp_default',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ece03e978d4',
    ),
    '646ece15df3b64' => 
    array (
      'type' => 'column-meta',
      'label' => 'Show Specials',
      'width' => '',
      'width_unit' => '%',
      'field' => 'property_show_specials',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ece15df3b64',
    ),
    '646ece24d126e8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Has Specials',
      'width' => '',
      'width_unit' => '%',
      'field' => 'has_specials',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ece24d126e8',
    ),
    '646ece338978d4' => 
    array (
      'type' => 'column-meta',
      'label' => 'Availability URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'availability_url',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ece338978d4',
    ),
    '646ece41add2f0' => 
    array (
      'type' => 'column-meta',
      'label' => 'Available Units',
      'width' => '',
      'width_unit' => '%',
      'field' => 'available_units',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ece41add2f0',
    ),
    '60492043ac8b44' => 
    array (
      'type' => 'field_60491fe331bce',
      'label' => 'External Image URL',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60492043ac8b44',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'off',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);