<?php

return array (
  'version' => '6.0.3',
  'title' => 'Manual entry',
  'type' => 'floorplans',
  'id' => '60490ab529970',
  'updated' => 1675222327,
  'columns' => 
  array (
    '6168d783f43958' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '70',
      'width_unit' => 'px',
      'use_icon' => '1',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6168d783f43958',
    ),
    '60a2bfa9d91688' => 
    array (
      'type' => 'field_60a2bf39efa3a',
      'label' => 'Images',
      'width' => '290',
      'width_unit' => 'px',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '8',
      'export' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '60a2bfa9d91688',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '350',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '61e0866a8ac084' => 
    array (
      'type' => 'field_61e0862111d74',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '4',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e0866a8ac084',
    ),
    '6168d75a6872b0' => 
    array (
      'type' => 'field_600ab10550e47',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6168d75a6872b0',
    ),
    '600b41d6cb794' => 
    array (
      'type' => 'field_600a5138d7e0b',
      'label' => 'Availability URL',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb794',
    ),
    '600b41d6cb796' => 
    array (
      'type' => 'field_600a5144d7e0c',
      'label' => '# Available',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb796',
    ),
    '600b41d6cb798' => 
    array (
      'type' => 'field_600a5157d7e0e',
      'label' => 'Beds',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb798',
    ),
    '600b41d6cb799' => 
    array (
      'type' => 'field_600a5151d7e0d',
      'label' => 'Baths',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb799',
    ),
    '600b41d6cb79e' => 
    array (
      'type' => 'field_600ab0d850e46',
      'label' => 'Minimum Sqft',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79e',
    ),
    '600b41d6cb79f' => 
    array (
      'type' => 'field_600ab0ad50e43',
      'label' => 'Maximum Sqft',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79f',
    ),
    '600b41d6cb7a1' => 
    array (
      'type' => 'field_600ab0ce50e45',
      'label' => 'Minimum Rent',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a1',
    ),
    '600b41d6cb7a2' => 
    array (
      'type' => 'field_600aafb250e42',
      'label' => 'Maximum Rent',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a2',
    ),
    '600b41d6cb7a3' => 
    array (
      'type' => 'field_600ab0c050e44',
      'label' => 'Minimum Deposit',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a3',
    ),
    '600b41d6cb7a5' => 
    array (
      'type' => 'field_600aaf6750e41',
      'label' => 'Maximum Deposit',
      'width' => '',
      'width_unit' => '%',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb7a5',
    ),
    '600b41d6cb79c' => 
    array (
      'type' => 'field_600a515fd7e0f',
      'label' => 'Has Specials',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '600b41d6cb79c',
    ),
    '6032102c8ef75' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'wp_default',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '6032102c8ef75',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
    'primary_column' => '',
  ),
);