<?php

return array (
  'version' => '6.1.1',
  'title' => 'Properties',
  'type' => 'properties',
  'id' => '615f620aeffb8',
  'updated' => 1684980750,
  'columns' => 
  array (
    '646ec17beb4394' => 
    array (
      'type' => 'column-meta',
      'label' => 'Images',
      'width' => '200',
      'width_unit' => 'px',
      'field' => 'images',
      'field_type' => 'library_id',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'media_link_to' => '',
      'number_of_items' => '3',
      'before' => '',
      'after' => '',
      'edit' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec17beb4394',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '275',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    '646ec09aaed918' => 
    array (
      'type' => 'column-meta',
      'label' => 'Property ID',
      'width' => '',
      'width_unit' => '%',
      'field' => 'property_id',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec09aaed918',
    ),
    '646ec049f89374' => 
    array (
      'type' => 'column-meta',
      'label' => 'Address',
      'width' => '',
      'width_unit' => '%',
      'field' => 'address',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec049f89374',
    ),
    '646ec0585f3b64' => 
    array (
      'type' => 'column-meta',
      'label' => 'City',
      'width' => '',
      'width_unit' => '%',
      'field' => 'city',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec0585f3b64',
    ),
    '646ec06499db24' => 
    array (
      'type' => 'column-meta',
      'label' => 'State',
      'width' => '',
      'width_unit' => '%',
      'field' => 'state',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec06499db24',
    ),
    '646ec0706e978c' => 
    array (
      'type' => 'column-meta',
      'label' => 'Zipcode',
      'width' => '',
      'width_unit' => '%',
      'field' => 'zipcode',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec0706e978c',
    ),
    '646ec07dd851ec' => 
    array (
      'type' => 'column-meta',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'latitude',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec07dd851ec',
    ),
    '646ec08aca3d70' => 
    array (
      'type' => 'column-meta',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'longitude',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec08aca3d70',
    ),
    '6074b80cfeb850' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Property types',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'propertytypes',
      'term_link_to' => '',
      'number_of_items' => '5',
      'separator' => 'comma',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b80cfeb850',
    ),
    '646ec14ba5a1cc' => 
    array (
      'type' => 'column-meta',
      'label' => 'Description',
      'width' => '200',
      'width_unit' => 'px',
      'field' => 'description',
      'field_type' => 'excerpt',
      'string_limit' => 'character_limit',
      'character_limit' => '60',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec14ba5a1cc',
    ),
    '6074b7fc5645a0' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Amenities',
      'width' => '130',
      'width_unit' => 'px',
      'taxonomy' => 'amenities',
      'term_link_to' => '',
      'number_of_items' => '5',
      'separator' => 'comma',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'export' => 'off',
      'sort' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6074b7fc5645a0',
    ),
    '646ec15aac49bc' => 
    array (
      'type' => 'column-meta',
      'label' => 'URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'url',
      'field_type' => 'link',
      'link_label' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec15aac49bc',
    ),
    '646ec16412f1a8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Email',
      'width' => '',
      'width_unit' => '%',
      'field' => 'email',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec16412f1a8',
    ),
    '646ec1aa86a7f0' => 
    array (
      'type' => 'column-meta',
      'label' => 'Phone',
      'width' => '',
      'width_unit' => '%',
      'field' => 'phone',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec1aa86a7f0',
    ),
    '646ec1b655c290' => 
    array (
      'type' => 'column-meta',
      'label' => 'Matterport code',
      'width' => '',
      'width_unit' => '%',
      'field' => 'matterport',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec1b655c290',
    ),
    '646ec1c667ae14' => 
    array (
      'type' => 'column-meta',
      'label' => 'Video',
      'width' => '',
      'width_unit' => '%',
      'field' => 'video',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec1c667ae14',
    ),
    '646ec1e4760418' => 
    array (
      'type' => 'column-meta',
      'label' => 'Pets',
      'width' => '',
      'width_unit' => '%',
      'field' => 'pets',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '646ec1e4760418',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'off',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'primary_column' => 'title',
    'filter_segment' => '',
  ),
);